const std = @import("std");
const testing = std.testing;
const gfx = @import("labelle-gfx");
const core = @import("labelle-core");
const sm = core.shader_material;
const ShaderBackend = struct {
    pub const DecodedImage = gfx.MockBackend.DecodedImage;
    pub const DecodedFont = gfx.MockBackend.DecodedFont;
    pub const FontBakeParams = gfx.MockBackend.FontBakeParams;
    pub const FontAtlas = gfx.MockBackend.FontAtlas;
    pub const Texture = gfx.MockBackend.Texture;
    pub const Color = gfx.MockBackend.Color;
    pub const eql = gfx.MockBackend.eql;
    pub const Rectangle = gfx.MockBackend.Rectangle;
    pub const Vector2 = gfx.MockBackend.Vector2;
    pub const Camera2D = gfx.MockBackend.Camera2D;
    pub const white = gfx.MockBackend.white;
    pub const black = gfx.MockBackend.black;
    pub const red = gfx.MockBackend.red;
    pub const green = gfx.MockBackend.green;
    pub const blue = gfx.MockBackend.blue;
    pub const transparent = gfx.MockBackend.transparent;
    pub const color = gfx.MockBackend.color;
    pub const DrawCall = gfx.MockBackend.DrawCall;
    pub const ShapeCall = gfx.MockBackend.ShapeCall;
    pub const CircleCall = gfx.MockBackend.CircleCall;
    pub const LineCall = gfx.MockBackend.LineCall;
    pub const TriangleCall = gfx.MockBackend.TriangleCall;
    pub const PolygonCall = gfx.MockBackend.PolygonCall;
    pub const TextCall = gfx.MockBackend.TextCall;
    pub const FontHandle = gfx.MockBackend.FontHandle;
    pub const BlendMode = gfx.MockBackend.BlendMode;
    pub const MeshCall = gfx.MockBackend.MeshCall;
    pub const Material = gfx.MockBackend.Material;
    pub const MaterialEffect = gfx.MockBackend.MaterialEffect;
    pub const MaterialUniforms = gfx.MockBackend.MaterialUniforms;
    pub const MaterialCall = gfx.MockBackend.MaterialCall;
    pub const RenderTargetId = gfx.MockBackend.RenderTargetId;
    pub const PostPass = gfx.MockBackend.PostPass;
    pub const PostPassKind = gfx.MockBackend.PostPassKind;
    pub const PostPassUniforms = gfx.MockBackend.PostPassUniforms;
    pub const RenderTargetCall = gfx.MockBackend.RenderTargetCall;
    pub const PostPassCall = gfx.MockBackend.PostPassCall;
    pub const CameraPass = gfx.MockBackend.CameraPass;
    pub const ViewportCall = gfx.MockBackend.ViewportCall;
    pub const initMock = gfx.MockBackend.initMock;
    pub const deinitMock = gfx.MockBackend.deinitMock;
    pub const resetMock = gfx.MockBackend.resetMock;
    pub const getCameraPasses = gfx.MockBackend.getCameraPasses;
    pub const getViewportCalls = gfx.MockBackend.getViewportCalls;
    pub const getFontAtlasUnloadCalls = gfx.MockBackend.getFontAtlasUnloadCalls;
    pub const getDrawCalls = gfx.MockBackend.getDrawCalls;
    pub const getDrawCallCount = gfx.MockBackend.getDrawCallCount;
    pub const getShapeCalls = gfx.MockBackend.getShapeCalls;
    pub const getShapeCallCount = gfx.MockBackend.getShapeCallCount;
    pub const getCircleCalls = gfx.MockBackend.getCircleCalls;
    pub const getCircleCallCount = gfx.MockBackend.getCircleCallCount;
    pub const getLineCalls = gfx.MockBackend.getLineCalls;
    pub const getLineCallCount = gfx.MockBackend.getLineCallCount;
    pub const getTriangleCalls = gfx.MockBackend.getTriangleCalls;
    pub const getTriangleCallCount = gfx.MockBackend.getTriangleCallCount;
    pub const getPolygonCalls = gfx.MockBackend.getPolygonCalls;
    pub const getPolygonCallCount = gfx.MockBackend.getPolygonCallCount;
    pub const getTextCalls = gfx.MockBackend.getTextCalls;
    pub const getTextCallCount = gfx.MockBackend.getTextCallCount;
    pub const getMeshCalls = gfx.MockBackend.getMeshCalls;
    pub const getMeshCallCount = gfx.MockBackend.getMeshCallCount;
    pub const getMaterialCalls = gfx.MockBackend.getMaterialCalls;
    pub const getMaterialCallCount = gfx.MockBackend.getMaterialCallCount;
    pub const getRenderTargetCalls = gfx.MockBackend.getRenderTargetCalls;
    pub const getRenderTargetCallCount = gfx.MockBackend.getRenderTargetCallCount;
    pub const getRenderTargetDestroyCount = gfx.MockBackend.getRenderTargetDestroyCount;
    pub const getActiveRenderTarget = gfx.MockBackend.getActiveRenderTarget;
    pub const getPostPassCalls = gfx.MockBackend.getPostPassCalls;
    pub const getPostPassCallCount = gfx.MockBackend.getPostPassCallCount;
    pub const setScreenSize = gfx.MockBackend.setScreenSize;
    pub const isInCameraMode = gfx.MockBackend.isInCameraMode;
    pub const drawTexturePro = gfx.MockBackend.drawTexturePro;
    pub const drawRectangleRec = gfx.MockBackend.drawRectangleRec;
    pub const drawCircle = gfx.MockBackend.drawCircle;
    pub const drawTriangle = gfx.MockBackend.drawTriangle;
    pub const drawPolygon = gfx.MockBackend.drawPolygon;
    pub const drawLine = gfx.MockBackend.drawLine;
    pub const drawText = gfx.MockBackend.drawText;
    pub const drawTextWithFont = gfx.MockBackend.drawTextWithFont;
    pub const drawMesh = gfx.MockBackend.drawMesh;
    pub const drawTextureProMaterial = gfx.MockBackend.drawTextureProMaterial;
    pub const materialSupported = gfx.MockBackend.materialSupported;
    pub const createRenderTarget = gfx.MockBackend.createRenderTarget;
    pub const beginRenderTarget = gfx.MockBackend.beginRenderTarget;
    pub const endRenderTarget = gfx.MockBackend.endRenderTarget;
    pub const drawRenderTarget = gfx.MockBackend.drawRenderTarget;
    pub const destroyRenderTarget = gfx.MockBackend.destroyRenderTarget;
    pub const applyPostPass = gfx.MockBackend.applyPostPass;
    pub const postPassSupported = gfx.MockBackend.postPassSupported;
    pub const loadTexture = gfx.MockBackend.loadTexture;
    pub const decodeImage = gfx.MockBackend.decodeImage;
    pub const uploadTexture = gfx.MockBackend.uploadTexture;
    pub const uploadTextureFiltered = gfx.MockBackend.uploadTextureFiltered;
    pub const getLastUploadFilter = gfx.MockBackend.getLastUploadFilter;
    pub const getFilteredUploadCount = gfx.MockBackend.getFilteredUploadCount;
    pub const unloadTexture = gfx.MockBackend.unloadTexture;
    pub const createDynamicTexture = gfx.MockBackend.createDynamicTexture;
    pub const updateTexture = gfx.MockBackend.updateTexture;
    pub const isCompressed = gfx.MockBackend.isCompressed;
    pub const uploadCompressed = gfx.MockBackend.uploadCompressed;
    pub const compressedDims = gfx.MockBackend.compressedDims;
    pub const conformanceFontBytes = gfx.MockBackend.conformanceFontBytes;
    pub const decodeFont = gfx.MockBackend.decodeFont;
    pub const uploadFontAtlas = gfx.MockBackend.uploadFontAtlas;
    pub const unloadFontAtlas = gfx.MockBackend.unloadFontAtlas;
    pub const beginMode2D = gfx.MockBackend.beginMode2D;
    pub const endMode2D = gfx.MockBackend.endMode2D;
    pub const setViewport = gfx.MockBackend.setViewport;
    pub const clearViewport = gfx.MockBackend.clearViewport;
    pub const getScreenWidth = gfx.MockBackend.getScreenWidth;
    pub const getScreenHeight = gfx.MockBackend.getScreenHeight;
    pub const screenToWorld = gfx.MockBackend.screenToWorld;
    pub const worldToScreen = gfx.MockBackend.worldToScreen;
    pub const setDesignSize = gfx.MockBackend.setDesignSize;
    var creates: u64 = 0;
    var destroys: usize = 0;
    var writes: usize = 0;
    var bound: core.BackendTextureId = .none;
    pub fn shaderMaterialSupported() bool {
        return true;
    }
    pub fn createShaderMaterial(desc: sm.Descriptor) !sm.Id {
        creates += 1;
        if (desc.textures.len > 0) bound = desc.textures[0].texture;
        return @enumFromInt(creates);
    }
    pub fn setShaderParameter(_: sm.Id, _: []const u8, _: []const f32) !void {
        writes += 1;
    }
    pub fn setShaderTexture(_: sm.Id, _: []const u8, texture: core.BackendTextureId) !void {
        bound = texture;
    }
    pub fn destroyShaderMaterial(_: sm.Id) void {
        destroys += 1;
    }
};
test "generic material uses typed registry resolution, executes draw, and rejects stale handles" {
    gfx.MockBackend.initMock(testing.allocator);
    defer gfx.MockBackend.deinitMock();
    ShaderBackend.creates = 0;
    ShaderBackend.destroys = 0;
    ShaderBackend.writes = 0;
    const R = gfx.RetainedEngineWith(ShaderBackend, gfx.DefaultLayers);
    var renderer = R.init(testing.allocator, .{});
    defer renderer.deinit();
    const texture = try renderer.loadTexture("texture.png");
    const id = try renderer.createShaderMaterial(.{ .shaders = .{ .spv = "fragment" }, .textures = &.{.{ .name = "s_mask", .texture = texture }} });
    try testing.expectEqual(renderer.nativeTextureId(texture).?, ShaderBackend.bound);
    try testing.expect(@intFromEnum(texture) != @intFromEnum(ShaderBackend.bound));
    try renderer.setShaderParameter(id, "u_time", &.{1});
    try testing.expectEqual(@as(usize, 1), ShaderBackend.writes);
    try renderer.setShaderTexture(id, "s_mask", texture);
    try testing.expectError(error.InvalidTexture, renderer.setShaderTexture(id, "s_mask", .invalid));
    renderer.createSprite(gfx.EntityId.from(1), .{ .material = .{ .shader = id } }, .{ .x = 0, .y = 0 });
    renderer.render();
    try testing.expectEqual(@as(usize, 1), gfx.MockBackend.getMaterialCallCount());
    try testing.expectEqual(id, gfx.MockBackend.getMaterialCalls()[0].material.shader);
    renderer.clearShaderMaterials();
    try testing.expectEqual(@as(usize, 1), ShaderBackend.destroys);
    try testing.expectError(error.InvalidHandle, renderer.setShaderParameter(id, "u_time", &.{2}));
    renderer.destroyShaderMaterial(id);
    try testing.expectEqual(@as(usize, 1), ShaderBackend.destroys);
}
test "generic facade reports unsupported instead of silently accepting material" {
    gfx.MockBackend.initMock(testing.allocator);
    defer gfx.MockBackend.deinitMock();
    var renderer = gfx.RetainedEngineWith(gfx.MockBackend, gfx.DefaultLayers).init(testing.allocator, .{});
    defer renderer.deinit();
    try testing.expect(!renderer.shaderMaterialSupported());
    try testing.expectError(error.Unsupported, renderer.createShaderMaterial(.{ .shaders = .{ .spv = "fragment" } }));
}
test "texture slot replacement invalidates dependent generic material before reuse" {
    gfx.MockBackend.initMock(testing.allocator);
    defer gfx.MockBackend.deinitMock();
    ShaderBackend.creates = 0;
    ShaderBackend.destroys = 0;
    var renderer = gfx.RetainedEngineWith(ShaderBackend, gfx.DefaultLayers).init(testing.allocator, .{});
    defer renderer.deinit();
    const texture = try renderer.loadTexture("a.png");
    const other = try renderer.loadTexture("b.png");
    var desc: gfx.ShaderMaterialDescriptor = .{ .shaders = .{ .spv = "fragment" }, .textures = &.{.{ .name = "s_mask", .texture = texture }} };
    const first = try renderer.createShaderMaterial(desc);
    renderer.unloadTexture(texture);
    _ = try renderer.loadTexture("replacement.png");
    try testing.expectError(error.InvalidHandle, renderer.setShaderParameter(first, "u_time", &.{0}));
    try testing.expectEqual(@as(usize, 1), ShaderBackend.destroys);
    desc.textures = &.{.{ .name = "s_mask", .texture = other }};
    const second = try renderer.createShaderMaterial(desc);
    const replacement = try ShaderBackend.loadTexture("new.png");
    try renderer.replaceTexture(other, replacement);
    try testing.expectError(error.InvalidHandle, renderer.setShaderTexture(second, "s_mask", other));
    try testing.expectEqual(@as(usize, 2), ShaderBackend.destroys);
}
test "successful texture setter transfers tracked dependency to new registry key" {
    gfx.MockBackend.initMock(testing.allocator);
    defer gfx.MockBackend.deinitMock();
    ShaderBackend.creates = 0;
    ShaderBackend.destroys = 0;
    var renderer = gfx.RetainedEngineWith(ShaderBackend, gfx.DefaultLayers).init(testing.allocator, .{});
    defer renderer.deinit();
    const a = try renderer.loadTexture("a.png");
    const b = try renderer.loadTexture("b.png");
    const id = try renderer.createShaderMaterial(.{ .shaders = .{ .spv = "fragment" }, .textures = &.{.{ .name = "s_mask", .texture = a }} });
    try renderer.setShaderTexture(id, "s_mask", b);
    renderer.unloadTexture(a);
    try renderer.setShaderParameter(id, "u_time", &.{0});
    renderer.unloadTexture(b);
    try testing.expectError(error.InvalidHandle, renderer.setShaderParameter(id, "u_time", &.{0}));
}
